name: TMoney
softdepend:
  - Vault
  - PlaceholderAPI
main: me.theseems.tmoney.TMoneyPlugin
version: 0.5D
api-version: '1.13'
commands:
  tmoney:
    usage: 'ยง7Type /tmoney help for help'
    description: 'ยง7A command managing TMoney plugin'
    permission: tmoney.use